# Generated by Django 3.2.18 on 2023-04-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='notice',
            field=models.CharField(max_length=20),
        ),
    ]
