# Generated by Django 3.2.18 on 2023-04-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='notice',
            field=models.BooleanField(default=False),
        ),
    ]
